### ISSUE TITLE
Add clarification about subcommittee

### ISSUE THREAD

**Issue by nlharris** [OBF/bosc_materials#14]
to BOSC review process doc

**Comment by cjfields** [comment]
I'll check into how other review committees go about this.

**Comment by nlharris** [comment]
is this the RoR committee? probably now sufficiently described in https://github.com/OBF/bosc_materials/blob/master/BOSC_review_process.md?

**Comment by cjfields** [comment]
@nlharris Yes, this is RoR and described in the link.  I'll close this, though it's possible we revisit this w/ Deepak's input from this last round and add to another ticket focusing on improving those docs. He wrote up some notes that could be useful to make the RoR easier in the future.  

Not sure if we have his Github ID?

**Comment by nlharris** [comment]
@deepakunni3 is Deepak's github account but not sure if he'll see this

**Comment by deepakunni3** [comment]
Thank you for tagging me to this ticket @nlharris @cjfields ! 

Yes, I do have some notes somewhere. I'll make a new PR to add some more thoughts and ideas to the ROR process :)

**Comment by cjfields** [comment]
@deepakunni3 that would be great! Maybe add this ticket as a reference (I think the URL link should work).

**Comment by nlharris** [comment]
Hi, this seems to have been closed as completed but I don't see the PR. @deepakunni3 can you point me to it? Thanks!

**Comment by deepakunni3** [comment]
@nlharris Thank you for reminding me about this. 

I see that the review_process.md is giving a high level overview. I think the content we have currently about ROR is sufficient at the moment. I did make a detailed SOP for the ROR but that might be useful for us to have within the org committee.
