### ISSUE TITLE
add license for BOSC 2021 logos

### ISSUE THREAD

**Issue by nlharris** [OBF/bosc_materials#17]
maybe http://creativecommons.org/licenses/by/4.0/ ? would like advice from someone who knows about licenses, such as @peterjc or @cjfields

**Comment by hlapp** [comment]
Ideally this would be consistent with the licenses on the OBF logos, BOSC pear, etc. I notice now though that apparently neither the obf-docs `logos/` directory nor the OBF home page says much about this 😔

That said, CC-BY 4.0 seems like a natural choice to me.

**Comment by peterjc** [comment]
The original BOSC logos probably predates CC-BY, but for the current one (not meaning this new map one) we can probably formally set a license with the authors.

**Comment by cjfields** [comment]
+1 for CC-BY 4.0.  @nlharris do you want a license added to just this directory?

**Comment by nlharris** [comment]
thanks, chris! whatever you think best. license just in this directory seems fine. should we also mention & link to the license in the README?

**Comment by cjfields** [comment]
Yes I think a link would be good though should have a copy in the repo:

https://choosealicense.com/licenses/cc-by-4.0/#

**Comment by cjfields** [comment]
@nlharris @peterjc made the changes and added the license, have a look (will leave this open for comments for now)

**Comment by nlharris** [comment]
for extra credit, can you make the readme more like https://github.com/OBF/bosc_materials/blob/master/logos/readme.md? 
the font is called SpaceGrotesk

**Comment by nlharris** [comment]
thanks for adding the license!

**Comment by cjfields** [comment]
No problem! Not sure if I should take on the extra credit or not 😉 ?

**Comment by nlharris** [comment]
yes please! 😀 🍐
