### ISSUE TITLE
change name of bosc_materials/logos to 2019-logos

### ISSUE THREAD

**Issue by nlharris** [OBF/bosc_materials#18]
there should be an easy way to change a folder name but i don't see how to do it in github; maybe it needs to be done from the command line or some git app? @cjfields can you change it?

**Comment by peterjc** [comment]
But we already have ``/logos/old_logos`` so wouldn't ``/logos/2019/`` be better if you want to retire some out of the way.

And put the new ones under ``/logos/2021/`` perhaps to preempt further musical chairs in future?

**Comment by peterjc** [comment]
P.S. Trivial with git at the command line, unsure if possible within GitHub on the browser

**Comment by cjfields** [comment]
> P.S. Trivial with git at the command line, unsure if possible within GitHub on the browser

Yep, `git mv`.  But there isn't a way to do it on Github that I know of.

**Comment by nlharris** [comment]
can one of you make it so?

**Comment by nlharris** [comment]
thanks, peter!

**Comment by peterjc** [comment]
#20 is fall out from this
