### ISSUE TITLE
logos not showing up in preview

### ISSUE THREAD

**Issue by nlharris** [OBF/bosc_materials#20]
https://github.com/OBF/bosc_materials/tree/master/logos/readme.md is supposed to have previews of the logos but they are not showing up, any idea what's wrong?

**Comment by nlharris** [comment]
@cjfields @peterjc

**Comment by peterjc** [comment]
I should have moved the README too, long term better than fixing the links.

**Comment by nlharris** [comment]
@peterjc  i'm confused. now https://github.com/OBF/bosc_materials/tree/master/logos has no current logos (just 2019 and old_logos subdirectories) and no README. https://github.com/OBF/bosc_materials/blob/master/logos/2019/README.md is good but i hadn't noticed that it became not good.

the new logos are slightly hidden away in https://github.com/OBF/bosc_materials/tree/master/2021/logos (harder to find than the old logos, which are in the top-level master/logos folder) and the README there is just the original placeholder one without the image previews.

possibly i'm seeing a stale version or something?

**Comment by peterjc** [comment]
I propose to move ``2021/logos/`` into ``logos/2021/`` to match?

There is indeed currently no README in the logos folder, it can be short and sweet saying see the sub-folders which are date based.

**Comment by nlharris** [comment]
> I propose to move 2021/logos/ into logos/2021/ to match?
sure, that would make more sense. can you do that?
