### ISSUE TITLE
add logo previews to readme

### ISSUE THREAD

**Issue by nlharris** [OBF/bosc_materials#21]
https://github.com/OBF/bosc_materials/blob/master/logos/2021/README.md

(i did the logo folder moving myself, from the command line. can someone else like @cjfields or @peterjc add the logo previews?)

**Comment by cjfields** [comment]
@nlharris did you mean something like this?

https://github.com/OBF/bosc_materials/tree/cjfields-patch-1/logos/2021

That is an example I made in a pull request using HTML to embed imaged, so it can be modified and probably made a little better (e.g. table with images and names, etc)

**Comment by nlharris** [comment]
yes! something like that! doesn't have to be fancy.

**Comment by cjfields** [comment]
all the images, or just a subset?

**Comment by nlharris** [comment]
i guess all, why not?

**Comment by nlharris** [comment]
i mean, one each of each different png -- no need to include svg or other formats.

**Comment by cjfields** [comment]
Okay, just made an update on the pull request.  Quick and dirty addition of all the pngs, we can probably prettify that later if needed.

**Comment by nlharris** [comment]
thanks, @cjfields
